Traceback (most recent call last):
  File "./survival_records_c.py", line 2257, in <module>
    main()
  File "./survival_records_c.py", line 2201, in main
    export_batch_text_google_spreadsheet_test(user, pw, gd_client = gd_client, curr_key = curr_key, curr_wksht_id = records_wksht)
  File "./survival_records_c.py", line 2022, in export_batch_text_google_spreadsheet_test
    cells = gd_client.GetCellsFeed(curr_key, wksht_id = curr_wksht_id, query=query)
  File "/usr/local/lib/python2.7/dist-packages/gdata/spreadsheet/service.py", line 221, in GetCellsFeed
    converter=gdata.spreadsheet.SpreadsheetsCellsFeedFromString)
  File "/usr/local/lib/python2.7/dist-packages/gdata/service.py", line 1108, in Get
    'reason': server_response.reason, 'body': result_body}
gdata.service.RequestError: {'status': 400, 'body': 'Invalid query parameter value for max-col.', 'reason': 'Bad Request'}
